Feature/task 1
Aleksey-Bortnik/JS-tasks pull request #1
Opened 2021-07-15 05:42 UTC by Aleksey-Bortnik

2021-07-15 07:18 UTC, angelinabylitskaya requested changes

2021-07-15 07:18 UTC, angelinabylitskaya commented on .husky/pre-commit
> +npm run lint:fix
Add prettier as well

2021-07-15 10:15 UTC, ElizavetaSelivanova commented on js-tasks/task1.js
> +
Try to simplify (reduce amount of code)

2021-07-15 10:15 UTC, ElizavetaSelivanova commented on .eslintignore
> +/.git
Add an empty line

2021-07-19 07:59 UTC, ElizavetaSelivanova requested changes

2021-07-19 07:59 UTC, ElizavetaSelivanova commented on js-tasks/task1.js
> +function summ() {
Add check for existence (if undefined -> return) to avoid errors

(*for every function)

2021-07-19 07:59 UTC, ElizavetaSelivanova commented on js-tasks/task1.spec.js
> +describe('Task 1.', () => {
Add some empty lines between logical blocks to make code more readable

2021-07-20 13:28 UTC, irina-chernik commented on js-tasks/task1.js
> +  if (a === null || typeof a === 'undefined') {
typeof here is not really neccesary and is not usually used to check for undefined value
here is more informantion about difference
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined

2021-07-21 07:54 UTC, irina-chernik approved these changes

2021-07-22 12:33 UTC, merged